# Generated by Django 3.2.5 on 2022-02-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('temp', models.IntegerField(null=True)),
                ('dev', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp', models.CharField(max_length=50, null=True)),
                ('emp_tempt', models.IntegerField(null=True)),
                ('tempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devi_name', models.CharField(max_length=50, null=True)),
                ('devi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.employee')),
            ],
        ),
    ]
